name: testing gh
on:
    push:
        branches:
            - 'gh-actions'
jobs:
    conditional_step:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 2
            - shell : pwsh
              id: check_file_changes
              run: |
                $diff = git diff --name-only HEAD^ HEAD